"$schema" = "http://json-schema.org/draft-07/schema#"
title = "CrashBot Config"
type = "object"
required = ["crashbot"]
additionalProperties = false

[properties.crashbot]
type = "object"
required = ["sign_rss_feed", "channel_id"]
additionalProperties = false

[properties.crashbot.properties.sign_rss_feed]
type = "string"
description = "The RSS feed URL to monitor."

[properties.crashbot.properties.channel_id]
type = "string"
description = "The Discord channel ID to post messages to."

[properties.crashbot.properties.check_interval_minutes]
type = "number"
description = "How often (in minutes) to check the RSS feed."


